#!/bin/bash
export PHC_REMOTE_SERVER=${PHC_SERVER_USER}@${PHC_SERVER_IP}
export PHC_WORKSPACE=/home/${PHC_SERVER_USER}/${PHC_DEST_FOLDER}
export CHH_REMOTE_SERVER=${CHH_SERVER_USER}@${CHH_SERVER_IP}
export CHH_WORKSPACE=/home/${CHH_SERVER_USER}/${CHH_DEST_FOLDER}